[project]
name = "pynn_example"
version = "0.1.0"
description = "minimal example o PyNN"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "jupyter",
    "matplotlib",
    "neuron>=8.2.6,<9.00",
    "numpy==1.26",
    "pynn",
    "pyneuroml>=1.3.15",
]